### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by snoopydooper** [estruyf/homebridge-solis-sensors#3]
Seem to have some API error:
>Error Unauthorized
>[12/6/2022, 12:24:13 PM] [@estruyf/homebridge-solis-sensors] No battery data found
>Error Unauthorized

I have followed the following process to get a new key.
>https://solis-service.solisinverters.com/support/solutions/articles/44002212561-api-access-soliscloud

Key and secret provided is actually same as I was using before.
API URL might be different now - https://www.soliscloud.com:13333/

Result is the same.

**Comment by estruyf** [comment]
APIs did not change, but it seems you now have to request access via a support ticket. 

> In order to get access please submit a ticket for API access [Submit a ticket : Service Centre (solisinverters.com)](https://solis-service.solisinverters.com/en/support/tickets/new).

Will try to submit a ticket as well, as I just noticed my app stopped as well. Wasn't home last week, so didn't check it.

**Comment by estruyf** [comment]
At least, it seems that it is so in my case.

![image](https://user-images.githubusercontent.com/2900833/205853396-a983de93-742d-475f-946c-26085942f632.png)

I tried to activate it myself, but that doesn't work anymore.

![image](https://user-images.githubusercontent.com/2900833/205853460-9cc5fe7c-7c0a-4e51-8ad9-2c55645842f9.png)

Once I get access, I can test it out again.

**Comment by estruyf** [comment]
@snoopydooper got API access again and switched to the `13333` port for the API, and it should be working. I released a new patch version, `0.1.1` with the port switch. Can you verify if it is also working on your end?

**Comment by helangen** [comment]
I am running v0.0.1-beta.2820195 and still get the same error

```
Error Unauthorized
[12/8/2022, 9:28:44 AM] [SolisSensors] No battery data found
```

I have the following config:

```
            "keyId": "*redacted*",
            "keySecret": "*redacted*",
            "stationId": "*redacted*",
            "platform": "SolisSensors",
            "batterySensor": false,
            "solarSensor": true,
            "netSensor": true,
            "loadSensor": true

```

I requested and got my API yesterday. Where do you get the stationID btw? Just to make sure I have the correct one.

**Comment by estruyf** [comment]
Latest beta version is: `0.1.1-beta.3637309225`

**Comment by helangen** [comment]
> Latest beta version is: `0.1.1-beta.3637309225`

Sorry, just saw that. Misread. I will try to update and let you know.

**Comment by helangen** [comment]
I now get this error on startup and HB just shuts down.

```
[12/8/2022, 10:04:41 AM] TypeError: Cannot read properties of null (reading 'power')
    at SolisBatteryAccessory.pollBatteryStatus (/var/lib/homebridge/node_modules/@estruyf/homebridge-solis-sensors/src/accesory/SolisBatteryAccessory.ts:115:64)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/8/2022, 10:04:42 AM] Got SIGTERM, shutting down Homebridge...
```

I have disabled the battery sensor (config above). Is this related to the new version?

**Comment by snoopydooper** [comment]
Working fine for me now. Thank you!!

**Comment by estruyf** [comment]
@helangen please check if you got the settings updated, as they did since `0.1.0` - example on the readme.

**Comment by helangen** [comment]
They should be as I posted above and I copied them from your README.md. What devices are supported? The error might be on my side assuming the wrong solar sensor are supporte.d

**Comment by Tangheta** [comment]
Same error for me
3/27/2023, 1:47:02 PM Solis Sensors Bridge SolisSensors ERROR No battery data found

**Comment by adisoruc** [comment]
hi, 
i have the same problem, 

Error Unauthorized
[11/23/2025, 1:55:26 PM] [@estruyf/homebridge-solis-sensors] No battery data found
Error Unauthorized
[11/23/2025, 1:56:27 PM] [@estruyf/homebridge-solis-sensors] No battery data found

also there is no data showing in the accessories tab

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/434310ed-d0a2-44a6-b693-6fd488682722" />

**Comment by adisoruc** [comment]
TypeError: Cannot read properties of null (reading 'power')
    at SolisBatteryAccessory.pollBatteryStatus (/usr/local/lib/node_modules/@estruyf/homebridge-solis-sensors/src/accesory/SolisBatteryAccessory.ts:115:64)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[11/23/2025, 2:16:08 PM] Got SIGTERM, shutting down Homebridge...
